### ISSUE TITLE
Docs: Frontend Library, Blackbox Frontend, Risiken und technische Schulden

### ISSUE THREAD

**Issue by JakWai01** [alphahorizonio/consumat.io#165]

**Comment by john-luck-pickerd** [comment]
![Blackbox_Frontend](https://user-images.githubusercontent.com/80920862/122606150-c2ee9280-d078-11eb-8f71-328d1b690877.png)

**Comment by helmrich** [comment]
# Dokumentation - Frontend
## 6.3 Blackbox Frontend
See @john-luck-pickerd's comment above.

## 9.1 Frameworks und Bibliotheken
### 9.1.1 Frontend
| Zweck          | Library                   | Begründung  |
| ----------------------- | ------------------------- | --- |
| JavaScript Superset     | TypeScript                | Uns war eine Typisierung, die in JavaScript ja nicht vorhanden ist, wichtig. Besonders im Zusammenspiel mit GraphQL war dies leicht zu ermöglichen, da das GraphQL-Schema auch typisiert ist.    |
| Frontend Library        | React                     | React benötigt kaum Einarbeitungszeit, da es uns erlaubt mithilfe der Syntax-Extension JSX, was im Prinzip wie eine Mischung aus HTML und JavaScript ist, schnell und einfach Komponenten zu erstellen. |
| React Framework        | Next.js                   | Next.js und das dazugehörige Ökosystem bietet uns viele Features, wie Authentifizierung, Routing und PWA-Support und ermöglicht uns ein schnelles und reibungsloses Deployment auf Vercel. |
| GraphQL Client          | Apollo                    | Apollo kommt mit eingebauter Integration für React und erlaubt es uns auf leichte Art und Weise mit Hooks deklarativ Daten abzurufen. |
| Code Generator          | GraphQL Code Generator    | Den GraphQL Code Generator verwenden wir, um aus unserem GraphQL-Schema und unseren Queries/Mutations automatisch richtig typisierte Apollo-Hooks zu bekommen. |
| CSS Framework          | Tailwind CSS             | Mit Tailwind CSS können wir mithilfe vieler vordefinierter Utility-Klassen in unserem JSX inline unsere Komponenten gestalten. |

## 10. Architekturprinzipien
| Prinzip/Pattern | Begründung       |
| --------------- | ---------------- |
| Data Provider   | Beim Data Provider Pattern findet das Datenmanagement in einer zentralen Komponente &#8212; dem Data Provider &#8212; statt. Komponenten innerhalb des Providers können auf die vom Provider zur Verfügung gestellten Daten zugreifen. Wir verwenden dieses Pattern in unserer Anwendung z.B., um mit dem von Apollo zur Verfügung gestellten `ApolloProvider` mit unseren GraphQL-Daten zu interagieren.             |
| Prop Drilling   | Das Prinzip des Prop Drillings geht einher mit der Benutzung von React. Prop Drilling beschreibt den Prozess des Leitens des Datenflusses durch den React Component Tree, welcher nur von den Parent-Komponenten zu den Child-Komponenten fließt. |

## 12. Risiken und technische Schulden
Eines der Hauptfeatures von Apollo ist die Cachingfunktionalität, bei welcher nach Mutations der Cache automatisch aktualisiert werden kann. Diese haben wir aber nicht verwendet, weswegen nun an manchen Stellen längere Ladezeiten entstehen. Darüber hinaus können Daten folglich nach dem Ausführen einer Mutation auch nicht automatisch aktualisiert werden.

**Comment by JakWai01** [comment]
Wow! Thanks for the effort :+1:
