### ISSUE TITLE
Design: User can search for content by name or genre

### ISSUE THREAD

**Issue by JakWai01** [alphahorizonio/consumat.io#19]
See #12 

![Screenshot from 2021-04-16 16-15-34](https://user-images.githubusercontent.com/59575534/115037988-5e278800-9ecf-11eb-985f-057dec7de605.png)
![image](https://user-images.githubusercontent.com/80920862/115145934-973d3500-a054-11eb-83eb-7a46089071ce.png)

**Comment by JakWai01** [comment]
@helmrich @john-luck-pickerd @lucas-goldner Could you maybe explain your choice of sort options further? What is the difference between "most_popular" and "most_relevant"? Furthermore, what does "suggested" do? If it suggests movies/TV Shows based on my input it probably shouldn't be a "sort_by" option because sorting only manipulates already existing results. I would be glad if you can help me out, so the API can be specified accordingly.

**Comment by john-luck-pickerd** [comment]
@JakWai01 most_relevant should only sort the results after the best match of the search term and the applied filters. most_recent, most_popular and top_rated should sort all results after the correspond field. E.g. for top_rated this is the voteAverage from tmdb.
And yeah; suggest should probably be an extra filter option and not under sort_by.

**Comment by john-luck-pickerd** [comment]
@JakWai01 Concernig most_relevant @helmrich suggested that popularity and rating could also influence the sorting of the results to a certain degree. I think for the beginning this isn't necessary, but if you want to figure out an algorithm that combines best match and popularity and maybe also rating this is up to you.

**Comment by helmrich** [comment]
> @JakWai01 Concernig most_relevant @helmrich suggested that popularity and rating could also influence the sorting of the results to a certain degree. I think for the beginning this isn't necessary, but if you want to figure out an algorithm that combines best match and popularity and maybe also rating this is up to you.

Indeed the `most_relevant` sort option is quite vague and could be implemented in a number of different ways by the backend team considering what really is *relevant to the user*. In my opinion it could for example be a combination of the search term, the applied filters, the `most_popular` value and the medium's rating or for example also a more personal relevance rating that's defined by similar media the user watched/liked/rated highly or belonging to a genre the user has consumed lots of other media of.

But like @john-luck-pickerd already said, in the beginning taking a simple approach of just saying accordance with search term + applied filters = relevance would also be just fine and the backend team could later adjust it to a more complex algorithm that takes into account some of the aforementioned or entirely different criteria if they feel like it.
