### ISSUE TITLE
Design:  Get details on a series or movie 

### ISSUE THREAD

**Issue by JakWai01** [alphahorizonio/consumat.io#21]
See #15 

![Screenshot from 2021-04-16 19-38-11](https://user-images.githubusercontent.com/59575534/115063028-51b12880-9eeb-11eb-9d4a-e10147f93a7f.png)

**Comment by JakWai01** [comment]
Could you maybe provide some more information concerning the cast? Is it really just a list of names like depicted in the design?

**Comment by helmrich** [comment]
@JakWai01 Right now the plan is to just display images and names of the cast. Further down the road it might also be interesting to have the roles of the cast (main/supporting) provided.
