### ISSUE TITLE
Frontend: Convert GraphQL schema to TypeScript types

### ISSUE THREAD

**Issue by john-luck-pickerd** [alphahorizonio/consumat.io#45]
@pojntfx Could you handle this or give us instructions on how to do it?

**Comment by pojntfx** [comment]
Pushed to the main branch, oops. See https://github.com/alphahorizonio/consumat.io-frontend/commit/15f081293eee62b5c43b69b82cfbb9d7eba4cdd2 for the integration. To prevent this in the future, branch protection for the `main` branch has been enabled.
