### ISSUE TITLE
Infrastructure: Keep GraphQL schema in Frontend repo in sync with API repo

### ISSUE THREAD

**Issue by helmrich** [alphahorizonio/consumat.io#46]
Is there a way to keep the `consumat-io.graphql` file inside of the `api` folder in the Frontend repo in sync with the corresponding file in the API repo? Maybe via submodules @pojntfx?

**Comment by pojntfx** [comment]
@helmrich I'd recommend manual syncing - this forces both teams to agree on API changes before implementing them. One is also implementing agains a _version_ of the API, so keeping it "in sync" would be incompatible versioning anyways.

**Comment by helmrich** [comment]
> @helmrich I'd recommend manual syncing - this forces both teams to agree on API changes before implementing them. One is also implementing against a _version_ of the API, so keeping it "in sync" would be incompatible with versioning anyways.

Good point, let's keep syncing it manually. :+1:
